Added button to test Microphone and display Cap
blackboard/BBDN-LTI-Tool-Provider-Node pull request #147
Opened 2023-03-14 11:37 UTC by abasith-bbdn

Additional two buttons added to test Micro Phone and Display capture

2023-03-20 15:37 UTC, abasith-bbdn commented
Additional two buttons added to test Micro Phone and Display capture

2023-03-20 16:04 UTC, subithamuniasamy approved these changes

2023-03-20 16:04 UTC, subithamuniasamy commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getUserMedia({ audio: true }). catch (
Do we need separate catch block , instead can't we add with line 104.

2023-03-20 17:01 UTC, adgilmore commented on public/src/components/pages/ltiAdvView.js
> +      .then(jwtPayload => {
Why is there a bunch of space added here?

2023-03-20 17:02 UTC, adgilmore approved these changes

2023-03-20 17:26 UTC, abasith-bbdn commented on public/src/components/pages/ltiAdvView.js
> +      .then(jwtPayload => {
Whitespace removed @adgilmore

2023-03-20 18:29 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getUserMedia({ audio: true }). catch (
Why was this marked as resolved? The question seems relevant for each of these blocks.

2023-03-20 18:31 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getDisplayMedia({ video: true }). catch (
Combine catch block with promise above rather than duplicating the call to the media API.

2023-03-20 18:32 UTC, varju commented on public/src/components/pages/ltiAdvView.js
Is there background to this change? I'm curious why this is useful to include in the LTI test tool.

2023-03-20 18:38 UTC, abasith-bbdn commented on public/src/components/pages/ltiAdvView.js
Yes @varju. 

What was the issue:

[LRN-180381](https://jira.bbpd.io/browse/LRN-180381) & [LRN-194962](https://jira.bbpd.io/browse/LRN-194962)
To address the defect, we must permit LTI iframe HTML tags with the “allow” attribute values “display-capture *” and “microphone *.”
The “display-capture *” attribute enables embedded content to capture the user’s device display, commonly used in video conferencing or screen sharing applications.
In contrast, the “microphone *” attribute enables embedded content to access the user’s microphone, frequently used in voice recognition, video or audio conferencing, and voice recording applications.
Although we have implemented changes in Learn and Ultra applications, we lack the ability to test the modifications in the local environment using the LTI admin tool.

What was the risk:

We do not currently have any functionality to test the changes using the LTI admin tool. As a result, we are unable to test the changes in the local environment and cannot proceed with QA branch testing.

How did we overcome that:

We have added further functionality to the LTI admin tool to test microphone and display capture access for a specific LTI iframe HTML tag. When the iframe is granted access to the microphone and display capture, an alert box indicating “access granted” will be displayed. Conversely, if access is denied, an error message will appear in the alert box.

2023-03-20 18:40 UTC, abasith-bbdn commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getDisplayMedia({ video: true }). catch (
@varju I have tried but it's throwing error that's why i have done separated catch.

2023-03-20 22:09 UTC, varju requested changes

2023-03-20 22:09 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +    const checkMicroPhone = () => {
Cosmetic: `checkMicroPhone` should be `checkMicrophone`, as microphone is one word.

2023-03-20 22:09 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +          alert('Microphone access granted!', stream);
The stream should be closed again after confirming it works, otherwise the microphone is left open. I just tested the following locally and think it's what you need:

```
const closeTracks = stream => {
  stream.getTracks().forEach(track => {
    if (track.readyState == 'live') {
      track.stop();
    }
  });
}

const checkMicrophone = () => {
  navigator.mediaDevices.getUserMedia({ audio: true })
    .then(stream => {
      alert('Microphone access granted');
      closeTracks(stream);
    })
    .catch(error => alert('Microphone access denied', error));
  };
```

2023-03-20 22:09 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getDisplayMedia({ video: true }). catch (
I don't see errors when I test locally. This worked fine for me (Chrome and Safari):

```
const checkDisplayCap = () => {
  navigator.mediaDevices.getDisplayMedia({ video: true })
    .then(stream => {
      alert('Display capture access granted');
      closeTracks(stream);
    })
    .catch(error => alert('Display capture access denied', error));
};
```

2023-03-21 04:32 UTC, abasith-bbdn commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getDisplayMedia({ video: true }). catch (
@varju Thanks for your valuable suggestion. I have done changes. Please check and merge this changes in master branch.

2023-03-21 04:36 UTC, abasith-bbdn commented on public/src/components/pages/ltiAdvView.js
> +          alert('Microphone access granted!', stream);
Changes done.

2023-03-21 05:18 UTC, athipazham approved these changes

2023-03-21 12:27 UTC, brianburdan approved these changes

2023-03-21 12:27 UTC, brianburdan commented on public/src/components/pages/ltiAdvView.js
> +      navigator.mediaDevices.getUserMedia({ audio: true })
Nit: Your alert strings for microphone end with `!`, and the display capture ones do not. Probably want to be consistent.

2023-03-21 12:27 UTC, brianburdan commented on public/src/components/pages/ltiAdvView.js
> +              <Button variant='contained' color='secondary' onClick={() => checkMicroPhone()}>Test MicroPhone</Button>
Same comment here from varju. `Microphone`

2023-03-21 19:36 UTC, varju approved these changes

2023-03-21 19:36 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +              <Button variant='contained' color='secondary' onClick={() => checkMicrophone()}>Test MicroPhone</Button>
```suggestion
              <Button variant='contained' color='secondary' onClick={() => checkMicrophone()}>Test Microphone</Button>
```

2023-03-21 19:36 UTC, varju commented on public/src/components/pages/ltiAdvView.js
> +    const checkDisplayCap = () => {
Cosmetic: It would be nice to rename this to `checkDisplayCapture` to match what the button says, and so it's more understandable to the reader.

2023-03-22 19:42 UTC, merged