AB#2012594 Handling 204 response status from LTI AGS implementation
blackboard/BBDN-LTI-Tool-Provider-Node pull request #162
Opened 2024-03-27 07:33 UTC by tsyed-bbdn

[AB#2012594](https://github.com/blackboard-learn/learn/pull/2464)

**Issue:**
LTI AGS implementation in learn was changed to send response status 204, which represents NO CONTENT, when the timestamp sent as part of input JSON is older than the already graded date. But the LTI testing tool does handle this new status code.

**RCA:**
On analysis found that the new status code change needs to be done in assign-grades.js

**Fix:**
Made changes to handle status code 204.

2024-03-27 07:35 UTC, abasith-bbdn approved these changes
Approved

2024-03-27 20:46 UTC, varju requested changes

2024-03-27 20:46 UTC, varju commented on server/src/app/assign-grades.js
> +          json = JSON.parse('{"status": "204", "message": "Score ignored as timestamp is earlier than the already graded date."}');
This message isn't 100% accurate. https://www.imsglobal.org/spec/lti-ags/v2p0#score-service-media-type-and-schema indicates 204 is a valid response at any time, even if the score is accepted.

How about this?
```suggestion
        } else if (response.statusCode === 204) {
          json = {"status": 204, "message": "No content"};
```

2024-03-28 05:57 UTC, tsyed-bbdn commented on server/src/app/assign-grades.js
> +          json = JSON.parse('{"status": "204", "message": "Score ignored as timestamp is earlier than the already graded date."}');
Hello @varju ,
Done in the latest commit.

2024-03-28 16:42 UTC, varju approved these changes

2024-03-28 16:42 UTC, merged